# Generated by Django 3.1.8 on 2021-11-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('count_click', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
